global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "kafka-exporter"
    static_configs:
      - targets: ["kafka-exporter:9308"]
  - job_name: "kafka"
    static_configs:
      - targets: ["broker-1:9111"]
      - targets: ["broker-2:9112"]
      - targets: ["broker-3:9113"]